// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Cleared.iOS
{
	public partial class CompanyViewController : UIViewController
	{
        public CompanyViewController() {}
		public CompanyViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
