// This file has been autogenerated from a class added in the UI designer.

using System;
using Cleared.Services;
using Foundation;
using UIKit;
using XAnimations;

namespace Cleared.iOS
{
	public partial class FeedbackViewController : UIViewController
	{
        FeedbackData Data = new FeedbackData();

		public FeedbackViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            thankYouText.Alpha = 0f;

			happy1.TouchUpInside += (sender, e) => { Data.Happy = 1; UpdateScreen(); happy1.CreateAnimator<TadaAnimator>().Animate(); };
			happy2.TouchUpInside += (sender, e) => { Data.Happy = 2; UpdateScreen(); happy2.CreateAnimator<WobbleAnimator>().Animate(); };
			happy3.TouchUpInside += (sender, e) => { Data.Happy = 3; UpdateScreen(); happy3.CreateAnimator<WaveAnimator>().Animate(); };
			happy4.TouchUpInside += (sender, e) => { Data.Happy = 4; UpdateScreen(); happy4.CreateAnimator<SwingAnimator>().Animate(); };
			happy5.TouchUpInside += (sender, e) => { Data.Happy = 5; UpdateScreen(); happy5.CreateAnimator<RubberBandAnimator>().Animate(); };

            sendButton.TouchUpInside += Send;
		}

        public override void ViewWillDisappear(bool animated)
        {
            base.ViewWillDisappear(animated);
        }

        async void Send(object sender, EventArgs e)
        {
            sendButton.Enabled = false;
            commentEdit.Editable = false;
            emailText.Enabled = false;
			happy1.Enabled = false;
			happy2.Enabled = false;
			happy3.Enabled = false;
			happy4.Enabled = false;
			happy5.Enabled = false;

            thankYouText.Alpha = 1f;

			await thankYouText.CreateAnimator<FadeInUpAnimator>()
				.SetDuration(0.3)
				.Animate();

            Data.Comment = commentEdit.Text;
            Data.Email = emailText.Text;
			await BrainCloudService.Current.AddFeedback(Data);

			thankYouText.CreateAnimator<TadaAnimator>()
				.SetRepeat()
				.Start();
        }

        void UpdateScreen()
		{
			happy1.Alpha = (Data.Happy == 1) ? 1f : 0.5f;
			happy2.Alpha = (Data.Happy == 2) ? 1f : 0.5f;
			happy3.Alpha = (Data.Happy == 3) ? 1f : 0.5f;
			happy4.Alpha = (Data.Happy == 4) ? 1f : 0.5f;
			happy5.Alpha = (Data.Happy == 5) ? 1f : 0.5f;

            commentEdit.ResignFirstResponder();     // dismiss keyboard
		}

	}
}
