// This file has been autogenerated from a class added in the UI designer.

using System;
using Cleared.Model;
using Foundation;
using UIKit;

namespace Cleared.iOS
{
	public partial class SelectGameCell : UICollectionViewCell
	{
        public const string CellID = "SelectGameCell";

        public GameDefinition GameDefinition { get; private set; }
        public GameHighScore HighScore { get; set; }

        public event EventHandler Tapped;

		public SelectGameCell (IntPtr handle) : base (handle)
		{
		}

        public void SetGame(GameDefinition game)
        {
            if (GameDefinition == null)
            {
                CellButton.TouchUpInside += (sender, e) => Tapped?.Invoke(this, new EventArgs());    
            }
            GameDefinition = game;
            CellButton.SetTitle(game.DisplayIndex.ToString(), UIControlState.Normal);
        }

        public void SetGameHighScore(GameHighScore highScore)
        {
            HighScore = highScore;
            CellButton.BackgroundColor = HighScore == null ? "#FFFFFF".ToUIColor(0.5f) : "#FFFFFF".ToUIColor(0f);
        }
	}
}
