// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreAnimation;
using Foundation;
using UIKit;
using XAnimations;
using Cleared.Model;
using Cleared.iOS.Engine;

namespace Cleared.iOS
{
	public partial class TapToPlayViewController : UIViewController
	{

        public event EventHandler Tapped;

        public TapToPlayViewController() {}
		public TapToPlayViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            View.UserInteractionEnabled = true;
            var tapGesture = new UITapGestureRecognizer(() => RaiseTapped() );
            View.AddGestureRecognizer(tapGesture);

            SoundButton.TouchUpInside += (sender, e) => 
            {
                GameData.Current.ToggleMusic();
                UpdateScreen();
			};

			UpdateScreen();

			logo.CreateAnimator<BounceInLeftAnimator>().Start();
            //MusicImage.CreateAnimator<BounceInDownAnimator>().SetStartDelay(0.2).Start();
            ArrowForward.CreateAnimator<BounceInUpAnimator>().SetStartDelay(0.4).Start();
        }

        void RaiseTapped()
        {
            Tapped?.Invoke(this, new EventArgs());
        }

        void UpdateScreen() 
        {
            if (GameData.Current.MuteMusic)
            {
                MusicImage.CreateAnimator<FadeToAnimator>()
                          .SetDestValue(0.2f)
                          .SetDuration(0.3f)
                          .Start();
                MusicEngine.Instance.StopMusic();
            }
            else
            {
                MusicImage.CreateAnimator<FadeToAnimator>()
                          .SetDestValue(0.6f)
                          .SetDuration(0.3f)
                          .Start();
                MusicEngine.Instance.PlayMusic("carefree.mp3");
            }
        }
	}
}
